### ISSUE TITLE
Cannot see upload logs from worker

### ISSUE THREAD

**Issue by cphl** [ICGC-TCGA-PanCancer/store-and-forward-workflow#6]
Upload logs are available but can only be seen if one enters the docker container for the tool (icgc/cli:1.1). It's located at `/collab/storage/logs/client.log` in the container.

It would be good to have them accessible from the worker (just like we can see download logs): copied out or sharing a mounted folder.

**Comment by niall-byrne** [comment]
There is already a proposed fix for this on the 1.0.9 release branch.

**Comment by cphl** [comment]
awesome
