### ISSUE TITLE
Workflow stops but doesn't "fail" if problem pulling docker image

### ISSUE THREAD

**Issue by cphl** [ICGC-TCGA-PanCancer/store-and-forward-workflow#7]
### Observations
- workflow doesn't appear to be doing anything
- slack reporter shows that it is at the download step
- no errors show in the /datastore/oozie.../generated-scripts/ logs
- check of docker containers and images shows:

```
$ docker ps -a
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS                    PORTS               NAMES
9d2a4fb31bce        pancancer/seqware_whitestar_pancancer:1.1.1   "seqware bundle launc"   21 hours ago        Up 21 hours                                   furious_blackwell
369aa7a9c110        seqware/seqware_whitestar:1.1.1               "/bin/bash"              21 hours ago        Exited (0) 21 hours ago                       lonely_varahamihira
bde7ea7e4728        pancancer/seqware_whitestar_pancancer:1.1.1   "/bin/bash"              21 hours ago        Exited (0) 21 hours ago                       suspicious_leakey
93d3b69856a1        seqware/seqware_whitestar:1.1.1               "/bin/bash"              12 days ago         Exited (0) 12 days ago                        romantic_mclean
6e4b128c0559        pancancer/seqware_whitestar_pancancer:1.1.1   "/bin/bash"              12 days ago         Exited (0) 12 days ago                        sharp_cori
$ docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
icgc/cli                                latest              0e5d39796c16        13 days ago         1.009 GB
<none>                                  <none>              94278f9644ca        3 weeks ago         294.2 MB
pancancer/seqware_whitestar_pancancer   1.1.1               ec5640650e0d        3 months ago        2.113 GB
seqware/seqware_whitestar               1.1.1               25c37e8ca531        3 months ago        1.565 GB
seqware/pancancer_upload_download       latest              e3447a54f1e0        3 months ago        415.1 MB
```
### Problem

Some issue pulling a docker image? (May be improved when I make a new worker base image with version tags.)
### Expected behaviour
- error out if the docker image can't be run for whatever reason?
- or error out if the expected docker container is not running at a step where it should be running?

**Comment by niall-byrne** [comment]
I thought we were pre-seeding the AMI's with the docker images we were using?
Isn't pulling an image on each run of the workflow a bit inefficient?

**Comment by cphl** [comment]
Yep. I see what the problem is now. Two parts. I had on the base image:
`seqware/pancancer_upload_download`
but the workflow wants
`pancancer/pancancer_upload_download`

Now I'm trying to do a manual pull of the one the workflow is looking for and it's hanging on this. Maybe the cause of the problem?

```
1.3: Pulling from pancancer/pancancer_upload_download
29460ac93442: Pull complete 
d2a0ecffe6fa: Layer already being pulled by another client. Waiting.
d338af9ecdc9: Layer already being pulled by another client. Waiting. 
7909da1938d9: Layer already being pulled by another client. Waiting. 
6916aef1ee5c: Layer already being pulled by another client. Waiting. 
d51fa068d78a: Layer already being pulled by another client. Waiting. 
16cb635a4370: Layer already being pulled by another client. Waiting. 
555ff7d73eaa: Layer already being pulled by another client. Waiting. 
492d306b8219: Layer already being pulled by another client. Waiting. 
43abcec8307f: Layer already being pulled by another client. Waiting. 
94278f9644ca: Layer already being pulled by another client. Waiting. 
c381083880ab: Layer already being pulled by another client. Waiting. 
4536f0c01ea1: Layer already being pulled by another client. Waiting. 
2d0df08588bf: Layer already being pulled by another client. Waiting. 
41235f030988: Layer already being pulled by another client. Waiting. 
032ff622b389: Layer already being pulled by another client. Waiting. 
30815eb4a00f: Layer already being pulled by another client. Waiting. 
3f2fb93d9ee8: Layer already being pulled by another client. Waiting. 
62e77dfe1a7a: Layer already being pulled by another client. Waiting. 
83e4dde6b9cf: Already exists 
b670fb0c7ecd: Already exists 
```

(hanging for 3 minutes now with no sign of activity, not sure how long to wait)

Second part is that I didn't have the version tags at the time of making the base image.

So far 2 workers with whatever this problem is. (Possibly related to 2 workers last week where @denis-yuen  and I were trying to pull the image and it just... wouldn't. Ended up failing those earlier 2, hoping fresh environment on retry will fix.)

Next worker base image will have version tags.

**Comment by niall-byrne** [comment]
We can manipulate the 'latest' to point to a particular tag as well on the docker hub side.  I'm not sure I understand the full extent of your issue, but if you need 'latest' to point to a particular version to ensure production is not blocked come see me, it's a very quick change.

**Comment by cphl** [comment]
There were extra fields that could be added to params.json to specify which docker images should be used for the workflow. These container fields have been added and now when the Deployer is called to make a worker than can be snapshotted (to make a worker base image), it makes the same additions as those on workers running workflows. This should make it so that docker images on the base image and what the true workers run is never out of sync.

```
   "containers": {
    "seqware_whitestar": {
      "name": "seqware_whitestar",
      "image_name": "pancancer/seqware_whitestar_pancancer:1.1.1"
    },
...
```

**Comment by denis-yuen** [comment]
Addendum: This might be this guy https://github.com/docker/docker/issues/12823
